### ISSUE TITLE
xUnit generation fails when stepResult is missing

### ISSUE THREAD

**Issue by MiS27** [Cognifide/aet#138]
Following exception is being thrown when trying to access xunit report for Test Suite Run with missing stepResults e.g. after some ProcessingError/timeout that would cause not persisting results:
```
| WARN  | qtp1838949591-92 | ServletHandler                   | pse.jetty.servlet.ServletHandler  505 | 70 - org.eclipse.jetty.util - 7.6.9.v20130131 | /xunit
java.lang.NullPointerException
	at com.cognifide.aet.xunit.MetadataToXUnitConverter.traverseSteps(MetadataToXUnitConverter.java:97)[86:com.cognifide.aet.rest-endpoint:2.1.1]
	at com.cognifide.aet.xunit.MetadataToXUnitConverter.convertStepsToXUnitCase(MetadataToXUnitConverter.java:91)[86:com.cognifide.aet.rest-endpoint:2.1.1]
	at com.cognifide.aet.xunit.MetadataToXUnitConverter.convertTestToXUnitSuite(MetadataToXUnitConverter.java:82)[86:com.cognifide.aet.rest-endpoint:2.1.1]
	at com.cognifide.aet.xunit.MetadataToXUnitConverter.convert(MetadataToXUnitConverter.java:68)[86:com.cognifide.aet.rest-endpoint:2.1.1]
	at com.cognifide.aet.rest.XUnitServlet.generateXUnitAndRespondWithIt(XUnitServlet.java:112)[86:com.cognifide.aet.rest-endpoint:2.1.1]
	at com.cognifide.aet.rest.XUnitServlet.process(XUnitServlet.java:85)[86:com.cognifide.aet.rest-endpoint:2.1.1]
	at com.cognifide.aet.rest.BasicDataServlet.doGet(BasicDataServlet.java:79)[86:com.cognifide.aet.rest-endpoint:2.1.1]
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:618)[243:org.apache.felix.http.servlet-api:1.1.2]
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:725)[243:org.apache.felix.http.servlet-api:1.1.2]
	at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:652)[81:org.eclipse.jetty.servlet:7.6.9.v20130131]
	at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:445)[81:org.eclipse.jetty.servlet:7.6.9.v20130131]
	at org.ops4j.pax.web.service.jetty.internal.HttpServiceServletHandler.doHandle(HttpServiceServletHandler.java:70)[99:org.ops4j.pax.web.pax-web-jetty:1.1.17]
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:137)[78:org.eclipse.jetty.server:7.6.9.v20130131]
	at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:556)[80:org.eclipse.jetty.security:7.6.9.v20130131]
	at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:227)[78:org.eclipse.jetty.server:7.6.9.v20130131]
	at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1044)[78:org.eclipse.jetty.server:7.6.9.v20130131]
	at org.ops4j.pax.web.service.jetty.internal.HttpServiceContext.doHandle(HttpServiceContext.java:124)[99:org.ops4j.pax.web.pax-web-jetty:1.1.17]
	at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:372)[81:org.eclipse.jetty.servlet:7.6.9.v20130131]
	at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:189)[78:org.eclipse.jetty.server:7.6.9.v20130131]
	at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:978)[78:org.eclipse.jetty.server:7.6.9.v20130131]
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:135)[78:org.eclipse.jetty.server:7.6.9.v20130131]
	at org.ops4j.pax.web.service.jetty.internal.JettyServerHandlerCollection.handle(JettyServerHandlerCollection.java:81)[99:org.ops4j.pax.web.pax-web-jetty:1.1.17]
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:116)[78:org.eclipse.jetty.server:7.6.9.v20130131]
	at org.eclipse.jetty.server.Server.handle(Server.java:367)[78:org.eclipse.jetty.server:7.6.9.v20130131]
	at org.eclipse.jetty.server.AbstractHttpConnection.handleRequest(AbstractHttpConnection.java:486)[78:org.eclipse.jetty.server:7.6.9.v20130131]
	at org.eclipse.jetty.server.AbstractHttpConnection.headerComplete(AbstractHttpConnection.java:926)[78:org.eclipse.jetty.server:7.6.9.v20130131]
	at org.eclipse.jetty.server.AbstractHttpConnection$RequestHandler.headerComplete(AbstractHttpConnection.java:988)[78:org.eclipse.jetty.server:7.6.9.v20130131]
	at org.eclipse.jetty.http.HttpParser.parseNext(HttpParser.java:640)[73:org.eclipse.jetty.http:7.6.9.v20130131]
	at org.eclipse.jetty.http.HttpParser.parseAvailable(HttpParser.java:235)[73:org.eclipse.jetty.http:7.6.9.v20130131]
	at org.eclipse.jetty.server.AsyncHttpConnection.handle(AsyncHttpConnection.java:82)[78:org.eclipse.jetty.server:7.6.9.v20130131]
	at org.eclipse.jetty.io.nio.SelectChannelEndPoint.handle(SelectChannelEndPoint.java:628)[72:org.eclipse.jetty.io:7.6.9.v20130131]
	at org.eclipse.jetty.io.nio.SelectChannelEndPoint$1.run(SelectChannelEndPoint.java:52)[72:org.eclipse.jetty.io:7.6.9.v20130131]
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:608)[70:org.eclipse.jetty.util:7.6.9.v20130131]
	at org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:543)[70:org.eclipse.jetty.util:7.6.9.v20130131]
	at java.lang.Thread.run(Thread.java:745)[:1.7.0_79]
```

**Comment by Skejven** [comment]
Fixed in #184
