### ISSUE TITLE
Integration tests - error while cucumber report generation

### ISSUE THREAD

**Issue by joannajasnowska** [Cognifide/aet#287]
### Version used

* master

### Context of the issue/feature

In aet sanity functional tests cucumber reports are not generated : there is an error:

`net.masterthought.cucumber.ValidationException: File '/var/lib/jenkins/jobs/AET/jobs/aet-sanity-functional-integration/builds/1679/cucumber-html-reports/.cache/report/test-report-20180712-073703.869-0001.json' is not proper Cucumber report!
	at net.masterthought.cucumber.ReportParser.parseForFeature(ReportParser.java:87)
	at net.masterthought.cucumber.ReportParser.parseJsonFiles(ReportParser.java:58)
	at net.masterthought.cucumber.ReportBuilder.generateReports(ReportBuilder.java:87)
	at net.masterthought.jenkins.CucumberReportPublisher.generateReport(CucumberReportPublisher.java:174)
	at net.masterthought.jenkins.CucumberReportPublisher.perform(CucumberReportPublisher.java:112)
	at hudson.tasks.BuildStepCompatibilityLayer.perform(BuildStepCompatibilityLayer.java:78)
	at hudson.tasks.BuildStepMonitor$1.perform(BuildStepMonitor.java:20)
	at hudson.model.AbstractBuild$AbstractBuildExecution.perform(AbstractBuild.java:779)
	at hudson.model.AbstractBuild$AbstractBuildExecution.performAllBuildSteps(AbstractBuild.java:720)
	at hudson.maven.MavenModuleSetBuild$MavenModuleSetBuildExecution.post2(MavenModuleSetBuild.java:1067)
	at hudson.model.AbstractBuild$AbstractBuildExecution.post(AbstractBuild.java:665)
	at hudson.model.Run.execute(Run.java:1753)
	at hudson.maven.MavenModuleSetBuild.run(MavenModuleSetBuild.java:544)
	at hudson.model.ResourceController.execute(ResourceController.java:98)
	at hudson.model.Executor.run(Executor.java:405)
Caused by: com.fasterxml.jackson.databind.JsonMappingException: Can not deserialize instance of net.masterthought.cucumber.json.Feature[] out of START_OBJECT token
 at [Source: java.io.InputStreamReader@745ff9c0; line: 1, column: 1]
	at com.fasterxml.jackson.databind.JsonMappingException.from(JsonMappingException.java:270)
	at com.fasterxml.jackson.databind.DeserializationContext.reportMappingException(DeserializationContext.java:1234)
	at com.fasterxml.jackson.databind.DeserializationContext.handleUnexpectedToken(DeserializationContext.java:1122)
	at com.fasterxml.jackson.databind.DeserializationContext.handleUnexpectedToken(DeserializationContext.java:1075)
	at com.fasterxml.jackson.databind.deser.std.ObjectArrayDeserializer.handleNonArray(ObjectArrayDeserializer.java:275)
	at com.fasterxml.jackson.databind.deser.std.ObjectArrayDeserializer.deserialize(ObjectArrayDeserializer.java:179)
	at com.fasterxml.jackson.databind.deser.std.ObjectArrayDeserializer.deserialize(ObjectArrayDeserializer.java:20)
	at com.fasterxml.jackson.databind.ObjectMapper._readMapAndClose(ObjectMapper.java:3798)
	at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:2887)
	at net.masterthought.cucumber.ReportParser.parseForFeature(ReportParser.java:81)
	... 14 more`

This is probably the result of running cucumber and junit tests in parallel.

**Comment by tkaik** [comment]
Hi @joannajasnowska 

After running functional tests, the Cucumber report in JSON format is generated in: 
`integration-tests/sanity-functional/target/filtering.json` file, as configured in [this](https://github.com/Cognifide/aet/blob/master/integration-tests/sanity-functional/src/test/java/com/cognifide/aet/sanity/functional/cucumber/Filtering.java) file

It seems that your Jenkins job is trying to load the JSON file from `integration-tests/sanity-functional/target/cucumber-html-reports/` directory - you need to change the configuration to load the `filtering.json` file instead.

I'm attaching a screenshot with an example configuration of Cucumber reports plugin in a Jenkins job:
![aet json report location](https://user-images.githubusercontent.com/8331703/43716996-596b866e-9986-11e8-8e44-de383e4107d8.png)

Regards
